use std::fmt;
use std::ops::Index;
use std::sync::Arc;

use hypermath::{Float, Matrix, pga};

use crate::{
    AbstractGroupLut, FactorGroupIsometries, Group, GroupError, GroupResult, IsometryGroup,
    PerGenerator,
};

/// [Coxeter group], which is a group generated by mirror reflections.
///
/// [Coxeter matrixes][Coxeter matrix] are [symmetric] and all entries along the
/// diagonal are 1. An entry of `n` at `(i, j)` indicates that mirrors `i` and
/// `j` are separated by an angle of `π/n`.
///
/// All entries along the diagonal are 1. Entries adjacent to the diagonal
/// correspond to the numbers in a linear Schläfli symbol.
///
/// This type is relatively cheap to clone.
///
/// [Coxeter matrix]:
///     https://en.wikipedia.org/wiki/Coxeter_group#Coxeter_matrix_and_Schl%C3%A4fli_matrix
/// [Coxeter group]: https://en.wikipedia.org/wiki/Coxeter_group
/// [symmetric]: https://en.wikipedia.org/wiki/Symmetric_matrix
#[derive(Clone)]
pub struct CoxeterMatrix {
    /// Name, for a named Coxeter group.
    name: Option<(char, u16)>,
    /// Linear indices, for a linear Coxeter group.
    linear_indices: Option<Box<[u16]>>,
    /// Number of generators.
    generator_count: u8,
    /// Coxeter matrix.
    matrix: Box<[u16]>,

    /// Upper-triangular matrix whose columns are the normal vectors to the
    /// mirrors of the coxeter group.
    ///
    /// This is `None` if the Coxeter group is infinite.
    mirrors: Option<Matrix>,

    /// Matrix whose columns form a basis where each `i`th basis vector is
    /// parallel to all mirror hyperplanes except the `i`th and whose dot
    /// product with the normal vector for the `i`th mirror is 1.
    ///
    /// This is useful for interpreting [Dynkin notation].
    ///
    /// This is `None` if the Coxeter group is infinite.
    ///
    /// [Dynkin notation]:
    ///     https://bendwavy.org/klitzing/explain/dynkin-notation.htm
    mirror_basis: Option<Matrix>,
}

impl fmt::Debug for CoxeterMatrix {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CoxeterMatrix")
            .field("name", &self.name)
            .field("linear_indices", &self.linear_indices)
            .field("generator_count", &self.generator_count)
            .field("matrix", &self.matrix)
            .field("mirrors", &self.mirrors)
            .field("mirror_basis", &self.mirror_basis)
            .finish()
    }
}

impl fmt::Display for CoxeterMatrix {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Coxeter group ")?;
        if let Some((chr, n)) = self.name {
            write!(f, "{chr}{n}")
        } else if let Some(linear_indices) = &self.linear_indices {
            write!(f, "{linear_indices:?}")
        } else {
            write!(f, "with {} generators", self.generator_count)
        }
    }
}

impl Index<[u8; 2]> for CoxeterMatrix {
    type Output = u16;

    #[track_caller]
    fn index(&self, [i, j]: [u8; 2]) -> &Self::Output {
        assert!(i < self.generator_count, "index out of range");
        assert!(j < self.generator_count, "index out of range");
        &self.matrix[i as usize * self.generator_count as usize + j as usize]
    }
}

impl CoxeterMatrix {
    /// Returns the trivial Coxeter group.
    pub fn trivial() -> Self {
        Self {
            name: None,
            linear_indices: None,
            generator_count: 0,
            matrix: Box::from([]),
            mirrors: Some(Matrix::ident(0)),
            mirror_basis: Some(Matrix::ident(0)),
        }
    }

    /// Constructs a Coxeter group from a linear Schläfli symbol.
    pub fn new_linear(indices: impl Into<Box<[u16]>>) -> GroupResult<Self> {
        let indices = indices.into();
        let generator_count = try_ndim_from(indices.len() + 1)?;
        let mut ret = Self::from_matrix_fn(generator_count, |i, j| {
            if i + 1 == j {
                indices[i as usize] // off-diagonals
            } else {
                2 // others
            }
        })?;
        ret.linear_indices = Some(indices);
        Ok(ret)
    }

    fn linear_named(chr: char, n: u16, indices: impl Into<Box<[u16]>>) -> Self {
        Self::new_linear(indices)
            .expect("error constructing Coxeter group")
            .with_name(chr, n)
    }

    /// Constructs and validates a Coxeter group from a function that returns
    /// each element in the Coxeter matrix.
    ///
    /// The function `f` is only ever called for `i < j`.
    pub fn from_matrix_fn(
        generator_count: u8,
        mut f: impl FnMut(u8, u8) -> u16,
    ) -> GroupResult<Self> {
        let matrix: Box<[u16]> = itertools::iproduct!(0..generator_count, 0..generator_count)
            .map(|(i, j)| match i.cmp(&j) {
                std::cmp::Ordering::Less => f(i, j),
                std::cmp::Ordering::Equal => 1,
                std::cmp::Ordering::Greater => f(j, i),
            })
            .collect();

        // Calculate mirror vectors.
        let mirrors = compute_mirrors(generator_count, |i, j| {
            matrix[i as usize * generator_count as usize + j as usize]
        });

        let mirror_basis = mirrors.as_ref().and_then(|m| m.transpose().inverse());

        let ret = Self {
            name: None,
            linear_indices: None,
            generator_count,
            matrix,
            mirrors,
            mirror_basis,
        };

        // Validate indices.
        for i in 0..generator_count {
            for j in 0..=i {
                let is_positive_integer = ret[[i, j]] >= 1;
                let is_on_diagonal = i == j;
                let is_one = ret[[i, j]] == 1;
                let is_symmetric = ret[[i, j]] == ret[[j, i]];
                if !is_positive_integer || is_on_diagonal != is_one || !is_symmetric {
                    return Err(GroupError::BadCD);
                }
            }
        }

        Ok(ret)
    }

    /// Returns the number of generators in the coxeter group.
    pub fn generator_count(&self) -> u8 {
        self.generator_count
    }

    /// Returns a matrix whose columns are the Euclidean mirror vectors, or an
    /// error if the group is hyperbolic.
    pub fn mirrors(&self) -> GroupResult<&Matrix> {
        self.mirrors.as_ref().ok_or(GroupError::HyperbolicCD)
    }

    /// Returns a matrix whose columns for the mirror basis, or an error if the
    /// group is not spherical.
    ///
    /// Each `i`th basis vector of the mirror basis is parallel to all mirror
    /// hyperplanes except the `i`th, and its dot product with the `i`th mirror
    /// vector is 1. The basis vectors are not necessarily unit-length.
    ///
    /// This is useful for interpreting [Dynkin notation].
    ///
    /// This is `None` if the Coxeter group is infinite.
    ///
    /// [Dynkin notation]:
    ///     https://bendwavy.org/klitzing/explain/dynkin-notation.htm
    pub fn mirror_basis(&self) -> GroupResult<&Matrix> {
        self.mirror_basis.as_ref().ok_or(if self.mirrors.is_some() {
            GroupError::EuclideanCD
        } else {
            GroupError::HyperbolicCD
        })
    }

    /// Returns the transform for each mirror, or an error if the group is not
    /// finite (spherical).
    pub fn generator_transforms(&self) -> GroupResult<PerGenerator<pga::Motor>> {
        self.mirrors()?
            .cols()
            .map(pga::Motor::vector_reflection)
            .collect::<Option<_>>()
            .ok_or(GroupError::BadMotor)
    }

    /// Returns a generating set for the orientation-preserving subgroup of the
    /// group, or an error if the group is hyperbolic.
    pub fn chiral_generator_transforms(&self) -> GroupResult<PerGenerator<pga::Motor>> {
        let mut mirror_generators = self.generator_transforms()?.into_values();
        let Some(first) = mirror_generators.next() else {
            return Ok(PerGenerator::new());
        };
        Ok(mirror_generators.map(|g| g * &first).collect())
    }

    fn abstract_group_lut(&self) -> GroupResult<AbstractGroupLut> {
        super::todd_coxeter::construct_group(self.to_string(), self)
    }

    /// Returns the abstract group.
    pub fn group(&self) -> GroupResult<Group> {
        self.abstract_group_lut()?.try_into()
    }

    /// Constructs the full group structure with isometries.
    pub fn isometry_group(&self) -> GroupResult<IsometryGroup> {
        let group = self.abstract_group_lut()?;
        let mirror_generators = self.generator_transforms()?;
        let isometries =
            FactorGroupIsometries::from_generators_unchecked(&group, &mirror_generators);
        IsometryGroup::from_factors([(Arc::new(group), Arc::new(isometries))])
    }

    /// Constructs the full chiral group structure with isometries using an
    /// _O(n)_ algorithm, where _n_ is the order of the group.
    pub fn chiral_isometry_group(&self) -> GroupResult<IsometryGroup> {
        IsometryGroup::from_generators(
            format!("chiral {self}"),
            self.chiral_generator_transforms()?,
        )
    }
}

/// Constructors for every finite Coxeter group by their names
impl CoxeterMatrix {
    fn with_name(mut self, chr: char, n: u16) -> Self {
        self.name = Some((chr, n.into()));
        self
    }

    /// Returns A`n`, the symmetry of an `n`-dimensional simplex.
    ///
    /// Returns an error if `n < 1`.
    #[allow(non_snake_case)]
    pub fn A(n: u8) -> GroupResult<Self> {
        if n < 1 {
            return Err(GroupError::BadCD);
        }
        Ok(Self::linear_named('A', n as u16, vec![3; n as usize - 1]))
    }

    /// Returns B`n`, the symmetry an `n`-dimensional hypercube.
    ///
    /// Returns an error if `n < 2`.
    #[allow(non_snake_case)]
    pub fn B(n: u8) -> GroupResult<Self> {
        if n < 2 {
            return Err(GroupError::BadCD);
        }
        let mut indices = vec![3; n as usize - 1];
        indices[0] = 4;
        Ok(Self::linear_named('B', n as u16, indices))
    }

    /// Returns D`n`.
    ///
    /// Returns an error if `n < 4`.
    #[allow(non_snake_case)]
    pub fn D(n: u8) -> GroupResult<Self> {
        if n < 4 {
            return Err(GroupError::BadCD);
        }
        Ok(Self::from_matrix_fn(n, |i, j| {
            if i == 0 && j == 2 {
                3 // branch
            } else if i > 0 && i + 1 == j {
                3 // line
            } else {
                2 // no edges elsewhere
            }
        })?
        .with_name('D', n as u16))
    }

    /// Returns E6.
    #[allow(non_snake_case)]
    pub fn E6() -> Self {
        Self::E(6)
    }

    /// Returns E7.
    #[allow(non_snake_case)]
    pub fn E7() -> Self {
        Self::E(7)
    }

    /// Returns E6.
    #[allow(non_snake_case)]
    pub fn E8() -> Self {
        Self::E(8)
    }

    /// Returns E`n`, where `6 <= n <= 8`.
    #[allow(non_snake_case)]
    fn E(n: u8) -> Self {
        Self::from_matrix_fn(n, |i, j| {
            if i == 0 && j == 3 {
                3 // branch
            } else if i > 0 && i + 1 == j {
                3 // line
            } else {
                2 // no edges elsewhere
            }
        })
        .expect("error constructing Coxeter group En")
        .with_name('E', n as u16)
    }

    /// Returns F4, the symmetry of the 24-cell.
    #[allow(non_snake_case)]
    pub fn F4() -> Self {
        Self::linear_named('F', 4, [3, 4, 3])
    }

    /// Returns G2, the symmetry of the hexagon. It is equivalent to I6.
    #[allow(non_snake_case)]
    pub fn G2() -> Self {
        Self::linear_named('G', 2, [6])
    }

    /// Returns H2, the symmetry of the pentagon. It is equivalent to I5.
    #[allow(non_snake_case)]
    pub fn H2() -> Self {
        Self::linear_named('H', 2, [5])
    }

    /// Returns H3, the symmetry of the dodecahedron.
    #[allow(non_snake_case)]
    pub fn H3() -> Self {
        Self::linear_named('H', 3, [5, 3])
    }

    /// Returns H4, the symmetry of the 120-cell.
    #[allow(non_snake_case)]
    pub fn H4() -> Self {
        Self::linear_named('H', 4, [5, 3, 3])
    }

    /// Returns I`n`, the symmetry of an `n`-gon.
    ///
    /// Returns an error if `n < 2`.
    #[allow(non_snake_case)]
    pub fn I(n: u16) -> GroupResult<Self> {
        if n < 2 {
            return Err(GroupError::BadCD);
        }
        Ok(Self::linear_named('I', n, [n]))
    }
}

fn try_ndim_from(ndim: impl TryInto<u8>) -> GroupResult<u8> {
    ndim.try_into().map_err(|_| GroupError::TooHighDimensional)
}

fn compute_mirrors(generator_count: u8, index_fn: impl Fn(u8, u8) -> u16) -> Option<Matrix> {
    // The final mirror vectors will look like this, with each column as a
    // vector:
    //
    // ```
    // [ ? ? ? ? ? ]
    // [ 0 ? ? ? ? ]
    // [ 0 0 ? ? ? ]
    // [ 0 0 0 ? ? ]
    // [ 0 0 0 0 ? ]
    // ```
    //
    // If this matrix is `Lᵀ` then `L Lᵀ = A`, where `A` is the Schläfli
    // matrix of the Coxeter-Dynkin diagram. This is a Cholesky
    // decomposition. We use the Cholesky–Banachiewicz algorithm.
    // https://en.wikipedia.org/wiki/Cholesky_decomposition#Computation
    //
    // Each entry of the Schläfli matrix is `-2*cos(π/m)` where `m` is the
    // corresponding entry of the Coxeter matrix.
    let mut mirrors = Matrix::zero(generator_count);
    for i in 0..generator_count {
        for j in 0..=i {
            let mut sum = 0.0;
            for k in 0..j {
                sum += mirrors.get(i, k) * mirrors.get(j, k);
            }

            let mirror_dot = -(std::f64::consts::PI as Float / index_fn(i, j) as Float).cos();
            *mirrors.get_mut(i, j) = if i == j {
                // If this sqrt fails, then the group needs hyperbolic space.
                hypermath::util::try_sqrt(mirror_dot - sum)?
            } else {
                1.0 / mirrors.get(j, j) * (mirror_dot - sum)
            };
        }
    }
    Some(mirrors)
}

#[cfg(test)]
mod tests {
    use std::f64::consts::PI;

    use hypermath::{VectorRef, assert_approx_eq};

    use super::*;

    #[test]
    fn test_coxeter_mirror_basis() -> eyre::Result<()> {
        for result in [
            CoxeterMatrix::A(0),
            CoxeterMatrix::B(0),
            CoxeterMatrix::B(1),
            CoxeterMatrix::D(0),
            CoxeterMatrix::D(1),
            CoxeterMatrix::D(2),
            CoxeterMatrix::D(3),
            CoxeterMatrix::I(0),
            CoxeterMatrix::I(1),
        ] {
            assert!(matches!(result, Err(GroupError::BadCD)));
        }

        for coxeter_matrix in [
            CoxeterMatrix::A(1)?,
            CoxeterMatrix::A(2)?,
            CoxeterMatrix::A(3)?,
            // CoxeterMatrix::A(255)?, // too slow!
            CoxeterMatrix::B(2)?,
            CoxeterMatrix::B(3)?,
            CoxeterMatrix::B(4)?,
            CoxeterMatrix::B(5)?,
            // CoxeterMatrix::B(255)?, // too slow!
            CoxeterMatrix::D(4)?,
            CoxeterMatrix::D(5)?,
            // CoxeterMatrix::D(255)?, // too slow!
            CoxeterMatrix::E6(),
            CoxeterMatrix::E7(),
            CoxeterMatrix::E8(),
            CoxeterMatrix::F4(),
            CoxeterMatrix::G2(),
            CoxeterMatrix::H2(),
            CoxeterMatrix::H3(),
            CoxeterMatrix::H4(),
            CoxeterMatrix::I(2)?,
            CoxeterMatrix::I(3)?,
            CoxeterMatrix::I(255)?,
            CoxeterMatrix::I(u16::MAX)?,
        ] {
            println!("Testing {coxeter_matrix}");

            // Check mirror matrix.
            let m = coxeter_matrix.mirrors()?;
            for (i, c1) in m.cols().enumerate() {
                for (j, c2) in m.cols().enumerate() {
                    let angle = PI as Float / coxeter_matrix[[i as u8, j as u8]] as Float;
                    assert_approx_eq!(-angle.cos(), c1.dot(c2));
                }
            }

            // Check mirror basis.
            let b = coxeter_matrix.mirror_basis()?;
            for (i, basis_vector) in b.cols().enumerate() {
                for (j, mirror_vector) in m.cols().enumerate() {
                    let dot_product = basis_vector.dot(mirror_vector);
                    if i == j {
                        assert_approx_eq!(1.0, dot_product);
                    } else {
                        assert_approx_eq!(0.0, dot_product);
                    }
                }
            }
        }

        Ok(())
    }
}
