---
# no version here, so we can see a missing "version" tag in user prefs
show_welcome_at_startup: true
info:
  metric: STM
  keybinds_reference:
    function: false
    navigation: false
    numpad: false
    opacity: 0.95
    max_font_size: 1.5
  modifier_toggles: false
gfx:
  fps_limit: 60
  msaa: true
interaction:
  confirm_discard_only_when_scrambled: true
  drag_sensitivity: 0.7
  realign_on_release: false
  realign_on_keypress: true
  smart_realign: true
  dynamic_twist_speed: true
  twist_duration: 0.2
  other_anim_duration: 0.15
opacity:
  base: 1.0
  ungripped: 0.3
  hidden: 0.1
  selected: 1.0
  unhide_grip: false
  save_opacity_in_piece_filter_preset: false
outlines:
  default_size: 1.0
  hidden_size: 1.0
  hovered_size: 3.0
  selected_size: 2.0
  default_color: "#000000"
  hidden_color: "#000000"
  hovered_color: "#ffffff"
  selected_sticker_color: "#ff7700"
  selected_piece_color: "#bbbb00"
view_3d:
  pitch: 35.0
  yaw: -20.0
  roll: 0.0
  scale: 1.25
  fov_3d: 15.0
  fov_4d: 30.0
  align_h: 0.0
  align_v: 0.0
  show_frontfaces: true
  show_backfaces: false
  clip_4d_backfaces: true
  clip_4d_behind_camera: true
  show_internals: true
  facet_shrink: 0.0
  sticker_shrink: 0.0
  piece_explode: 0.2
  outline_thickness: 1.0
  light_ambient: 1.0
  light_directional: 1.0
  light_pitch: 35.0
  light_yaw: 0.0
  active_preset:
    preset_name: Default
    pitch: 35.0
    yaw: -20.0
    roll: 0.0
    scale: 1.25
    fov_3d: 15.0
    fov_4d: 30.0
    align_h: 0.0
    align_v: 0.0
    show_frontfaces: true
    show_backfaces: false
    clip_4d_backfaces: true
    clip_4d_behind_camera: true
    facet_shrink: 0.03
    sticker_shrink: 0.05
    piece_explode: 0.0
    outline_thickness: 1.0
    light_ambient: 1.0
    light_directional: 1.0
    light_pitch: 35.0
    light_yaw: 0.0
  presets:
    - preset_name: Default
      pitch: 35.0
      yaw: -20.0
      roll: 0.0
      scale: 1.25
      fov_3d: 15.0
      fov_4d: 30.0
      align_h: 0.0
      align_v: 0.0
      show_frontfaces: true
      show_backfaces: false
      clip_4d_backfaces: true
      clip_4d_behind_camera: true
      show_internals: true
      facet_shrink: 0.03
      sticker_shrink: 0.05
      piece_explode: 0.0
      outline_thickness: 1.0
      light_ambient: 1.0
      light_directional: 1.0
      light_pitch: 35.0
      light_yaw: 0.0
    - preset_name: Unfolded (back)
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
      scale: 3.0
      fov_3d: 60.0
      fov_4d: 30.0
      align_h: 0.0
      align_v: 0.0
      show_frontfaces: false
      show_backfaces: true
      clip_4d_backfaces: true
      clip_4d_behind_camera: true
      show_internals: false
      facet_shrink: 0.4
      sticker_shrink: 0.2
      piece_explode: 0.0
      outline_thickness: 1.0
      light_ambient: 1.0
      light_directional: 1.0
      light_pitch: 35.0
      light_yaw: 0.0
    - preset_name: Unfolded (front)
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
      scale: 3.0
      fov_3d: -60.0
      fov_4d: 30.0
      align_h: 0.0
      align_v: 0.0
      show_frontfaces: true
      show_backfaces: false
      clip_4d_backfaces: true
      clip_4d_behind_camera: true
      show_internals: false
      facet_shrink: 0.4
      sticker_shrink: 0.2
      piece_explode: 0.0
      outline_thickness: 1.0
      light_ambient: 1.0
      light_directional: 1.0
      light_pitch: 35.0
      light_yaw: 0.0
view_4d:
  pitch: 35.0
  yaw: -45.0
  roll: 0.0
  scale: 1.0
  fov_3d: 0.0
  fov_4d: 30.0
  align_h: 0.0
  align_v: 0.0
  show_frontfaces: true
  show_backfaces: true
  clip_4d_backfaces: true
  clip_4d_behind_camera: true
  show_internals: false
  facet_shrink: 0.7
  sticker_shrink: 0.3
  piece_explode: 0.0
  outline_thickness: 1.0
  light_ambient: 1.0
  light_directional: 1.0
  light_pitch: 65.0
  light_yaw: -55.0
  active_preset:
    preset_name: Default
    pitch: 35.0
    yaw: -45.0
    roll: 0.0
    scale: 1.0
    fov_3d: 0.0
    fov_4d: 30.0
    align_h: 0.0
    align_v: 0.0
    show_frontfaces: true
    show_backfaces: true
    clip_4d_backfaces: true
    clip_4d_behind_camera: true
    show_internals: false
    facet_shrink: 0.7
    sticker_shrink: 0.3
    piece_explode: 0.0
    outline_thickness: 1.0
    light_ambient: 1.0
    light_directional: 1.0
    light_pitch: 65.0
    light_yaw: -55.0
  presets:
    - preset_name: Default
      pitch: 35.0
      yaw: -45.0
      roll: 0.0
      scale: 1.0
      fov_3d: 0.0
      fov_4d: 30.0
      align_h: 0.0
      align_v: 0.0
      show_frontfaces: true
      show_backfaces: true
      clip_4d_backfaces: true
      clip_4d_behind_camera: true
      show_internals: false
      facet_shrink: 0.7
      sticker_shrink: 0.3
      piece_explode: 0.0
      outline_thickness: 1.0
      light_ambient: 1.0
      light_directional: 1.0
      light_pitch: 65.0
      light_yaw: -55.0
colors:
  background: "#444444"
  blind_face: "#cccccc"
  blindfold: false
piece_filters: ~
global_keybinds: []
puzzle_keybinds: ~
mousebinds: []
