---
# `version` is not needed for defaults
info:
  metric: STM
  keybinds_reference:
    function: false
    navigation: false
    numpad: false
    opacity: 0.95
    max_font_size: 1.5
  modifier_toggles: false
image_generator:
  filename: output.png
  width: 1024
  height: 1024
animation:
  last_loaded: Medium
  presets:
    Slow:
      dynamic_twist_speed: true
      twist_duration: 1.0
      blocking_anim_duration: 2.0
      twist_interpolation: cosine
    Medium:
      dynamic_twist_speed: true
      twist_duration: 0.2
      blocking_anim_duration: 1.0
      twist_interpolation: cosine
    Fast:
      dynamic_twist_speed: true
      twist_duration: 0.1
      blocking_anim_duration: 0.5
      twist_interpolation: cosine
    Instant:
      dynamic_twist_speed: true
      twist_duration: 0.0
      blocking_anim_duration: 0.25
      twist_interpolation: cosine
interaction:
  last_loaded: Default
  presets:
    Default:
      confirm_discard_only_when_scrambled: true
      drag_sensitivity: 0.7
      scale_twist_drag_by_radius: false
      realign_on_release: false
      realign_on_keypress: true
      smart_realign: true
styles:
  dark_background_color: '#1b1b1b'
  light_background_color: '#f8f8f8'
  internals_color: '#444444'
  blocking_outline_color: '#ff0000'
  blocking_outline_size: 5.0
  default:
    interactable: true
    face_opacity: 1.0
    face_color:
      mode: sticker
    outline_opacity: 1.0
    outline_size: 0.5
    outline_color:
      mode: fixed
      color: '#000000'
    outline_lighting: false
  gripped:
    interactable: true
    face_opacity: 1.0
    outline_opacity: 1.0
    outline_size: 1.0
  ungripped:
    interactable: false
    face_opacity: 0.3
    outline_opacity: 0.3
    outline_size: 0.0
  hovered_piece:
    interactable: true
    face_opacity: 1.0
    outline_opacity: 1.0
    outline_size: 3.0
    outline_color:
      mode: fixed
      color: '#ffffff'
    outline_lighting: false
  selected_piece:
    interactable: true
    face_opacity: 1.0
    outline_opacity: 1.0
    outline_size: 0.2
    outline_color:
      mode: fixed
      color: '#66ccdd'
    outline_lighting: false
  blind:
    interactable: true
    face_opacity: 1.0
    face_color:
      mode: fixed
      color: '#cccccc'
    outline_opacity: 1.0
    outline_size: 1.0
    outline_color:
      mode: fixed
      color: '#000000'
    outline_lighting: false
custom_styles:
  last_loaded: Hidden
  presets:
    Hidden:
      interactable: false
      face_opacity: 0.1
      outline_opacity: 0.1
      outline_size: 0.0
view_3d:
  last_loaded: Default
  presets:
    Default:
      scale: 1.25
      fov_3d: 15.0
      fov_4d: 30.0
      show_frontfaces: true
      show_backfaces: false
      show_behind_4d_camera: false
      show_internals: true
      facet_shrink: 0.03
      sticker_shrink: 0.05
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 0.0
      outline_light_intensity: 1.0
      downscale_rate: 1
      downscale_interpolate: true
    Unfolded (back):
      scale: 3.0
      fov_3d: 60.0
      fov_4d: 30.0
      show_frontfaces: false
      show_backfaces: true
      show_behind_4d_camera: false
      show_internals: false
      facet_shrink: 0.4
      sticker_shrink: 0.2
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 0.0
      outline_light_intensity: 1.0
      downscale_rate: 1
      downscale_interpolate: true
    Unfolded (front):
      scale: 3.0
      fov_3d: -60.0
      fov_4d: 30.0
      show_frontfaces: true
      show_backfaces: false
      show_behind_4d_camera: false
      show_internals: false
      facet_shrink: 0.4
      sticker_shrink: 0.2
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 0.0
      outline_light_intensity: 1.0
      downscale_rate: 1
      downscale_interpolate: true
view_4d:
  last_loaded: Default
  presets:
    Default:
      scale: 1.0
      fov_3d: 0.0
      fov_4d: 60.0
      show_frontfaces: true
      show_backfaces: false
      show_behind_4d_camera: false
      show_internals: false
      gizmo_scale: 1.0
      facet_shrink: 0.7
      sticker_shrink: 0.3
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 1.0
      outline_light_intensity: 1.0
      downscale_rate: 1
      downscale_interpolate: true
    Contiguous pieces:
      scale: 1.0
      fov_3d: 0.0
      fov_4d: 20.0
      show_frontfaces: true
      show_backfaces: false
      show_behind_4d_camera: false
      show_internals: false
      gizmo_scale: 0.5
      facet_shrink: 0.0
      sticker_shrink: 0.4
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 1.0
      outline_light_intensity: 1.0
      downscale_rate: 1
      downscale_interpolate: true
color_palette:
  builtin_colors:
    White: '#ffffff'
    Gray: '#777777'
    Black: '#222222'
    Brown: '#885522'
    Red: '#cc3333'
    Orange: '#ff9922'
    # Amber: '#ffcc00'
    Yellow: '#ffff00'
    Green: '#88ee66'
    Teal: '#009977'
    Blue: '#33aaff'
    Purple: '#8822cc'
    Pink: '#ff66ff'
  builtin_color_sets:
    Mono Dyad:
      - '#ffffff'
      - '#595959'
    Mono Triad:
      - '#a5a5a5'
      - '#ffffff'
      - '#595959'
    Mono Tetrad:
      - '#a5a5a5'
      - '#ffffff'
      - '#595959'
      - '#343434'
    Red Dyad:
      - '#ff8a8a'
      - '#6d1616'
    Red Triad:
      - '#ff8a8a'
      - '#d33535'
      - '#6d1616'
    Red Tetrad:
      - '#ff8a8a'
      - '#d33535'
      - '#6d1616'
      - '#3b0606'
    Orange Dyad:
      - '#ffb663'
      - '#834d0e'
    Orange Triad:
      - '#ffb663'
      - '#f1870d'
      - '#834d0e'
    Orange Tetrad:
      - '#ffb663'
      - '#f1870d'
      - '#834d0e'
      - '#4d300e'
    Yellow Dyad:
      - '#f7f89b'
      - '#858628'
    Yellow Triad:
      - '#feffa2' # previously f7f89b
      - '#d9da53' # previously dcdd70
      - '#858628'
    Yellow Tetrad:
      - '#f7f89b'
      - '#dcdd70'
      - '#858628'
      - '#5a5b05'
    Green Dyad:
      - '#b1f79c'
      - '#2c7714'
    Green Triad:
      - '#b1f79c'
      - '#5eff27'
      - '#2c7714'
    Green Tetrad:
      - '#b1f79c'
      - '#5eff27'
      - '#2c7714'
      - '#14300a'
    Blue Dyad:
      - '#79c7ff'
      - '#09436d'
    Blue Triad:
      - '#79c7ff'
      - '#0481d7'
      - '#09436d'
    Blue Tetrad:
      - '#79c7ff'
      - '#0481d7'
      - '#09436d'
      - '#0b2638'
    Purple Dyad:
      - '#c18aff'
      - '#3f1075'
    Purple Triad:
      - '#c18aff'
      - '#7524d1'
      - '#3f1075'
    Purple Tetrad:
      - '#c18aff'
      - '#7524d1'
      - '#3f1075'
      - '#240648'
    Magenta Dyad:
      - '#ff8bf6'
      - '#691161'
    Magenta Triad:
      - '#ff8bf6'
      - '#cf21c1'
      - '#691161'
    Magenta Tetrad:
      - '#ff8bf6'
      - '#cf21c1'
      - '#691161'
      - '#370932'
    Blank Pentad:
      - '#000000'
      - '#000000'
      - '#000000'
      - '#000000'
      - '#000000'
    Blank Hexad:
      - '#000000'
      - '#000000'
      - '#000000'
      - '#000000'
      - '#000000'
      - '#000000'
global_keybinds: []
puzzle_keybinds: ~
mousebinds: []
