---
# no version here, so we can see a missing "version" tag in user prefs
info:
  metric: STM
  keybinds_reference:
    function: false
    navigation: false
    numpad: false
    opacity: 0.95
    max_font_size: 1.5
  modifier_toggles: false
gfx:
  fps_limit: 60
  msaa: true
interaction:
  last_loaded: Default
  presets:
    - preset_name: Default
      confirm_discard_only_when_scrambled: true
      drag_sensitivity: 0.7
      scale_twist_drag_by_radius: false
      realign_on_release: false
      realign_on_keypress: true
      smart_realign: true
      dynamic_twist_speed: true
      twist_duration: 0.2
      blocking_anim_duration: 1.0
      other_anim_duration: 0.15
styles:
  dark_background_color: "#1b1b1b"
  light_background_color: "#f8f8f8"
  internals_color: "#777777"
  blocking_color: "#ff0000"
  blocking_outline_size: 5.0
  default:
    interactable: true
    face_opacity: 1.0
    face_color: "#cccccc"
    face_sticker_color: true
    outline_opacity: 1.0
    outline_color: "#000000"
    outline_sticker_color: false
    outline_size: 0.5
  gripped:
    face_opacity: 1.0
    outline_opacity: 1.0
    outline_size: 1.0
  ungripped:
    interactable: false
    face_opacity: 0.3
    outline_opacity: 0.3
    outline_size: 0.0
  hovered_piece:
    face_opacity: 1.0
    outline_opacity: 3.0
    outline_color: "#ffffff"
    outline_sticker_color: false
    outline_size: 3.0
  hovered_sticker: {}
  selected_piece:
    face_opacity: 1.0
    outline_opacity: 1.0
    outline_color: "#66ccdd"
    outline_size: 0.2
  selected_sticker: {}
  hidden:
    interactable: false
    face_opacity: 0.1
    outline_opacity: 0.1
    outline_size: 0.0
  blind: {}
  custom: {}
view_3d:
  last_loaded: Default
  presets:
    - preset_name: Default
      scale: 1.25
      fov_3d: 15.0
      fov_4d: 30.0
      show_frontfaces: true
      show_backfaces: false
      show_behind_4d_camera: false
      show_internals: true
      facet_shrink: 0.03
      sticker_shrink: 0.05
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 0.0
      outline_light_intensity: 0.0
      downscale_rate: 1
      downscale_interpolate: true
    - preset_name: Unfolded (back)
      scale: 3.0
      fov_3d: 60.0
      fov_4d: 30.0
      show_frontfaces: false
      show_backfaces: true
      show_behind_4d_camera: false
      show_internals: false
      facet_shrink: 0.4
      sticker_shrink: 0.2
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 0.0
      outline_light_intensity: 0.0
      downscale_rate: 1
      downscale_interpolate: true
    - preset_name: Unfolded (front)
      scale: 3.0
      fov_3d: -60.0
      fov_4d: 30.0
      show_frontfaces: true
      show_backfaces: false
      show_behind_4d_camera: false
      show_internals: false
      facet_shrink: 0.4
      sticker_shrink: 0.2
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 0.0
      outline_light_intensity: 0.0
      downscale_rate: 1
      downscale_interpolate: true
view_4d:
  last_loaded: Default
  presets:
    - preset_name: Default
      scale: 1.0
      fov_3d: 0.0
      fov_4d: 60.0
      show_frontfaces: true
      show_backfaces: false
      show_behind_4d_camera: false
      show_internals: false
      gizmo_scale: 1.0
      facet_shrink: 0.7
      sticker_shrink: 0.3
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 1.0
      outline_light_intensity: 0.0
      downscale_rate: 1
      downscale_interpolate: true
    - preset_name: Contiguous pieces
      scale: 1.0
      fov_3d: 0.0
      fov_4d: 20.0
      show_frontfaces: true
      show_backfaces: false
      show_behind_4d_camera: false
      show_internals: false
      gizmo_scale: 0.5
      facet_shrink: 0.0
      sticker_shrink: 0.4
      piece_explode: 0.0
      light_pitch: 65.0
      light_yaw: -55.0
      face_light_intensity: 1.0
      outline_light_intensity: 0.0
      downscale_rate: 1
      downscale_interpolate: true
color_palette:
  singles:
    White: "#ffffff"
    Red: "#cc3333"
    Orange: "#ff9922"
    Yellow: "#ffff00"
    Green: "#88ee66"
    Cyan: "#00ffff"
    Blue: "#33aaff"
    Purple: "#8822cc"
    Magenta: "#ff00ff"
    Pink: "#ff66ff"
  sets:
    Mono Dyad:
      - "#ffffff"
      - "#595959"
    Red Dyad:
      - "#ff8a8a"
      - "#6d1616"
    Orange Dyad:
      - "#ffb663"
      - "#834d0e"
    Yellow Dyad:
      - "#f7f89b"
      - "#858628"
    Green Dyad:
      - "#b1f79c"
      - "#2c7714"
    Blue Dyad:
      - "#79c7ff"
      - "#09436d"
    Purple Dyad:
      - "#c18aff"
      - "#3f1075"
    Magenta Dyad:
      - "#ff8bf6"
      - "#691161"
    Mono Triad:
      - "#a5a5a5"
      - "#ffffff"
      - "#595959"
    Red Triad:
      - "#ff8a8a"
      - "#d33535"
      - "#6d1616"
    Orange Triad:
      - "#ffb663"
      - "#f1870d"
      - "#834d0e"
    Yellow Triad:
      - "#f7f89b"
      - "#dcdd70"
      - "#858628"
    Green Triad:
      - "#b1f79c"
      - "#5eff27"
      - "#2c7714"
    Blue Triad:
      - "#79c7ff"
      - "#0481d7"
      - "#09436d"
    Purple Triad:
      - "#c18aff"
      - "#7524d1"
      - "#3f1075"
    Magenta Triad:
      - "#ff8bf6"
      - "#cf21c1"
      - "#691161"
    Mono Tetrad:
      - "#a5a5a5"
      - "#ffffff"
      - "#595959"
      - "#343434"
    Red Tetrad:
      - "#ff8a8a"
      - "#d33535"
      - "#6d1616"
      - "#3b0606"
    Orange Tetrad:
      - "#ffb663"
      - "#f1870d"
      - "#834d0e"
      - "#4d300e"
    Yellow Tetrad:
      - "#f7f89b"
      - "#dcdd70"
      - "#858628"
      - "#5a5b05"
    Green Tetrad:
      - "#b1f79c"
      - "#5eff27"
      - "#2c7714"
      - "#14300a"
    Blue Tetrad:
      - "#79c7ff"
      - "#0481d7"
      - "#09436d"
      - "#0b2638"
    Purple Tetrad:
      - "#c18aff"
      - "#7524d1"
      - "#3f1075"
      - "#240648"
    Magenta Tetrad:
      - "#ff8bf6"
      - "#cf21c1"
      - "#691161"
      - "#370932"
piece_filters: ~
global_keybinds: []
puzzle_keybinds: ~
mousebinds: []
