use std::{fmt, sync::Arc};

use hypuz_util::ti::TypedIndex;

use super::*;

/// Subgroup of a [`Group`], represented as a [direct product] where each factor
/// group in the product is a factor of the overgroup.
///
/// Not all subgroups can be represented this way; only subgroups generated by
/// elements in the factor groups of the original group can be represented.
///
/// [direct product]: https://en.wikipedia.org/wiki/Direct_product_of_groups
pub struct ProductSubgroup {
    /// Group that this is a subgroup of.
    overgroup: Group,
    /// Generating set for the subgroup.
    generators: Vec<GroupElementId>,
    /// Number of elements in the subgroup.
    element_count: usize,
    /// Factor subgroups.
    factors: PerFactorGroup<Arc<AbstractSubgroup>>,
}

impl fmt::Debug for ProductSubgroup {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ProductSubgroup")
            .field("overgroup", &self.overgroup)
            .field("generators", &self.generators)
            .field("element_count", &self.element_count)
            .field("factors", &self.factors)
            .finish()
    }
}

impl ProductSubgroup {
    pub(crate) fn from_factors(
        overgroup: Group,
        factors: impl IntoIterator<Item = Arc<AbstractSubgroup>>,
    ) -> Self {
        let factors = PerFactorGroup::from_iter(factors);

        // Assert that `overgroup` matches the factor subgroups.
        debug_assert_eq!(
            overgroup.direct_product_decomposition().len(),
            factors.len()
        );
        #[cfg(debug_assertions)]
        for (overgroup_factor, factor) in itertools::zip_eq(
            overgroup.direct_product_decomposition().iter_values(),
            factors.iter_values(),
        ) {
            debug_assert!(Arc::ptr_eq(overgroup_factor, factor.overgroup()));
        }

        let generators = factors
            .iter_values()
            .flat_map(|s| s.generators())
            .copied()
            .collect();

        // This shouldn't overflow because it must be no larger than
        // `overgroup.element_count`.
        let element_count = factors
            .iter_values()
            .map(|s| s.element_count())
            .try_fold(1, usize::checked_mul)
            .filter(|n| n.saturating_sub(1) <= GroupElementId::MAX.0 as usize)
            .expect("too many group elements");

        Self {
            overgroup,
            generators,
            element_count,
            factors,
        }
    }

    /// Returns the factor subgroups that this group is a direct product of.
    pub(crate) fn direct_product_decomposition(&self) -> &PerFactorGroup<Arc<AbstractSubgroup>> {
        &self.factors
    }

    /// Returns the group that this is a subgroup of.
    pub fn overgroup(&self) -> &Group {
        &self.overgroup
    }

    /// Returns whether the subgroup is trivial (contains only the identity).
    pub fn is_trivial(&self) -> bool {
        self.element_count == 1
    }

    /// Returns a canonical generating set for the subgroup.
    pub fn generators(&self) -> &[GroupElementId] {
        &self.generators
    }

    /// Returns the number of elements in the subgroup.
    pub fn element_count(&self) -> usize {
        self.element_count
    }

    /// Returns whether `element` is in the subgroup.
    pub fn contains(&self, element: GroupElementId) -> bool {
        std::iter::zip(
            self.factors.iter_values(),
            self.overgroup.element_to_factors(element),
        )
        .all(|(factor_subgroup, factor_element)| factor_subgroup.contains(factor_element))
    }

    /// Returns a list of all the elements in the subgroup.
    ///
    /// NOTE: Be careful to only enumerate subgroups that are relatively small.
    /// Prefer [`Self::element_count()`] and [`Self::contains()`] when possible,
    /// as those are much faster.
    pub fn elements(&self) -> Vec<GroupElementId> {
        let mut ret = vec![GroupElementId::IDENTITY];

        for (factor, factor_subgroup) in &self.factors {
            if !factor_subgroup.is_trivial() {
                let stride = self.overgroup.strides()[factor];
                ret = itertools::iproduct!(ret, factor_subgroup.elements())
                    .map(|(e1, e2)| GroupElementId(e1.0 + e2.0 * stride))
                    .collect();
            }
        }

        ret
    }
}
