import math
from os import path

dir = path.dirname(path.realpath(__file__))


with open(path.join(dir, 'autogenerated_lookup_tables.rs'), 'w') as f:
    f.write("//! Autogenerated lookup tables for GA multivectors.\n")
    f.write("//!\n")
    f.write(f"//! Do not edit this file manually!\n")
    f.write(f"//! It is generated by `{path.basename(__file__)}`.\n")

    f.write("\n")
    f.write("/// Lookup table for the 'choose' function.\n")
    f.write("pub const N_CHOOSE_K: [[u8; 9]; 9] = [\n")
    for n in range(9):
        f.write("    [")
        f.write(", ".join(str(math.comb(n, k)) for k in range(9)))
        f.write("],\n")
    f.write("];\n")

    term_orders = [[] for _ in range(9)]
    for i in range(256):
        term_orders[i.bit_count()].append(str(i))
    f.write("\n")
    f.write("/// Lookup table for the ordering of terms in a GA multivector.\n")
    f.write("pub const MULTIVECTOR_TERM_ORDER: [&[u8]; 9] = [\n")
    for term_order in term_orders:
        f.write("    &[")
        f.write(", ".join(term_order))
        f.write("],\n")
    f.write("];\n")

# ncr_orders = [[] for _ in range(9)]
