[package]
name = "hyperspeedcube"
description = "Multidimensional twisty puzzle simulator"
version = "2.0.0-pre.15"
authors = ["HactarCE"]
edition.workspace = true
homepage = "https://ajfarkas.dev/hyperspeedcube/"
repository.workspace = true
keywords = ["cubing", "hypercubing", "rubik", "game", "4d"]
categories = ["games", "mathematics", "simulation"]
license = "GPL-2.0-or-later"

[lints]
workspace = true

[dependencies]
bitflags = "2.4.2"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
bytemuck = { version = "1.9.1", features = ["derive"] }
cgmath = "0.18.0"
colorous = "1.0.10"
comrak = "0.26.0"
config = { version = "0.13.1", features = ["preserve_order"] }
# Fork of color-eyre that does not re-export color_owo, which otherwise clogs editor completions
color-eyre = { git = "https://github.com/FlareFlo/color-eyre.git", rev = "3bc103d5ffd7e26a71a6894579ef721e7b6c3ce1", default-features = false, features = ["track-caller", "capture-spantrace"] }
empfindung = "0.2.6"
eyre = "0.6"
directories = "4.0.1"
env_logger = "0.10.0"
float-ord = "0.3.2"
getrandom = { version = "*", features = ["js"] } # TODO: prefer `rand` crate
image = "0.24.9"
include_dir = "0.7.4"
indexmap = { version = "2.4.0", features = ["serde"] } # must match serde_yml
instant = "0.1.12"
itertools = "0.13.0"
key-names = { git = "https://github.com/HactarCE/key-names.git", tag = "v1.5.1", features = ["winit"] }
lazy_static = "1.5.0"
log = "0.4.17"
monostate = "0.1.1"
names = { version = "0.14.0", default-features = false }
num_enum = "0.5.7"
oklab = "1.0.1"
once_cell = "1.9.0"
opener = { version = "0.7.0", default-features = false }
optick = { version = "1.3.4", optional = true }
optick-attr = { version = "0.3.0", optional = true }
parking_lot = "0.12.1"
png = "0.17.5"
pollster = "0.2.5"
rand = "*"
regex = "1.6.0"
rfd = "0.10.0"
rgb_crate = { package = "rgb", version = "*" } # as required by empfindung
send_wrapper = "0.6"
serde = { version = "1.0.144", features = ["derive"] }
serde_yml = "0.0.10"
smallvec = { version = "1.8.0", features = ["serde", "union"] }
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.44"
time = { version = "0.3.7", features = ["local-offset"] }

hypermath = { path = "../hypermath" }
hyperpuzzle = { path = "../hyperpuzzle" }
hypershape = { path = "../hypershape" }

# Windowing and UI (versions must match)
eframe = { version = "0.28.1", default-features = false, features = ["accesskit", "default_fonts", "wayland", "web_screen_reader", "wgpu", "x11"] }
egui = "0.28.1"
egui_dock = "0.13.0"
egui_extras = "0.28.1"
winit = { version = "0.29", features = ["serde"] } # must match eframe
wgpu = { version = "0.20.1", features = ["webgl"] } # must match eframe

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
human-panic = "1.0"
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
egui-winit = { version = "0.27.2", default-features = false, features = ["links"] }
js-sys = "=0.3.69"
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
web-sys = { version = "=0.3.69", features = [
    "CanvasRenderingContext2d",
    "Clipboard",
    "ClipboardEvent",
    "DataTransfer",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Storage",
    "Window",
] }

[features]
optick = ["dep:optick", "dep:optick-attr"]
deadlock_detection = ["parking_lot/deadlock_detection"]

[build-dependencies]
hyperstrings = { path = "../hyperstrings" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
FileDescription = "Hyperspeedcube"
ProductName = "Hyperspeedcube"
ProductVersion = "2.0.0-pre.15"
OriginalFilename = "hyperspeedcube.exe"
LegalCopyright = "Copyright © 2024 HactarCE"

[package.metadata.bundle]
name = "Hyperspeedcube"
identifier = "dev.ajfarkas.hyperspeedcube"
icon = ["resources/icon/*.png", "resources/icon/*.ico"]
copyright = "Copyright © 2024 HactarCE"
category = "Puzzle Game"
