[package]
name = "hyperspeedcube"
version = "1.0.0"
authors = ["HactarCE"]
edition = "2021"
description = "Multidimensional twisty puzzle simulator"
repository = "https://github.com/HactarCE/Hyperspeedcube/"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambassador = "0.3.1"
anyhow = "1.0.55"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc", "serde", "std"] }
bytemuck = { version = "1.9.1", features = ["derive"] }
cgmath = "0.18.0"
config = "0.13.1"
dark-light = "0.2.1"
directories = "4.0.1"
egui = "0.18.0"
egui_wgpu_backend = "0.18.0"
egui_winit_platform = { version = "0.15.0", features = ["clipboard", "webbrowser"] }
enum_dispatch = "0.3.8"
enum-iterator = "1.1.3"
env_logger = "0.9.0"
epi = "0.17.0"
hex = "0.4.3"
human-panic = "1.0.3"
itertools = "0.10.3"
key-names = { git = "https://github.com/HactarCE/key-names", tag = "v1.3.0", features = ["winit"] }
lazy_static = "1.4.0"
log = "0.4.16"
monostate = "0.1.1"
num_enum = "0.5.7"
once_cell = "1.9.0"
png = "0.17.5"
pollster = "0.2.5"
rand = "0.8.5"
regex = "1.6.0"
rfd = "0.10.0"
send_wrapper = "0.6.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
smallvec = { version = "1.8.0", features = ["serde"] }
strum = { version = "0.24.0", features = ["derive"] }
time = { version = "0.3.7", features = ["local-offset"] }
wgpu = "0.13"
winit = { version = "0.26.0", features = ["serde"] }

ndpuzzle = { path = "../ndpuzzle" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
FileDescription = "Hyperspeedcube"
ProductName = "Hyperspeedcube"
ProductVersion = "1.0.0"
OriginalFilename = "hyperspeedcube.exe"
LegalCopyright = "Copyright © 2022 HactarCE"

[package.metadata.bundle]
name = "Hyperspeedcube"
identifier = "io.github.hactarce.hyperspeedcube"
icon = ["resources/icon/*.png", "resources/icon/*.ico"]
copyright = "Copyright © 2022 HactarCE"
category = "Puzzle Game"
