[package]
name = "hyperspeedcube"
description = "Multidimensional twisty puzzle simulator"
version = "2.0.0-pre.10"
authors = ["HactarCE"]
edition.workspace = true
homepage = "https://ajfarkas.dev/hyperspeedcube/"
repository.workspace = true
keywords = ["cubing", "hypercubing", "rubik", "game", "4d"]
categories = ["games", "mathematics", "simulation"]
license = "CC-BY-NC-SA-4.0"

[lints]
workspace = true

[dependencies]
bitflags = "2.4.2"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
bytemuck = { version = "1.9.1", features = ["derive"] }
cgmath = "0.18.0"
colorous = "1.0.10"
config = "0.13.1"
color-eyre = "0.6"
eyre = "0.6"
directories = "4.0.1"
enum-iterator = "1.4.0"
env_logger = "0.10.0"
rand = "*"
getrandom = { version = "*", features = ["js"] } # TODO: prefer `rand` crate
hex = "0.4.3"
include_dir = "0.7.3"
indexmap = { version = "2.2.5", features = ["serde"] }
instant = "0.1.12"
itertools = "0.10.3"
key-names = { git = "https://github.com/HactarCE/key-names", tag = "v1.5.1", features = ["winit"] }
lazy_static = "1.4.0"
log = "0.4.17"
monostate = "0.1.1"
num_enum = "0.5.7"
once_cell = "1.9.0"
opener = "0.7.0"
optick = { version = "1.3.4", optional = true }
optick-attr = { version = "0.3.0", optional = true }
parking_lot = "0.12.1"
png = "0.17.5"
pollster = "0.2.5"
regex = "1.6.0"
rfd = "0.10.0"
send_wrapper = "0.6"
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.8.23"
smallvec = { version = "1.8.0", features = ["serde", "union"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.44"
time = { version = "0.3.7", features = ["local-offset"] }
wgpu = { version = "0.19.4", features = ["webgl"] }

hypermath = { path = "../hypermath" }
hyperpuzzle = { path = "../hyperpuzzle" }
hypershape = { path = "../hypershape" }

# Windowing and UI (versions must match)
eframe = { version = "0.27.2", default-features = false, features = ["accesskit", "default_fonts", "wayland", "web_screen_reader", "wgpu", "x11"] }
egui = "0.27.2"
egui_dock = "0.12.0"
egui_extras = "0.27.2"
winit = { version = "0.29", features = ["serde"] } # must match eframe

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
human-panic = "1.0"
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
egui-winit = { version = "0.27.2", default-features = false, features = ["links"] }
js-sys = "=0.3.69"
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
web-sys = { version = "=0.3.69", features = [
    "CanvasRenderingContext2d",
    "Clipboard",
    "ClipboardEvent",
    "DataTransfer",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Storage",
    "Window",
] }

[features]
optick = ["dep:optick", "dep:optick-attr"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
FileDescription = "Hyperspeedcube"
ProductName = "Hyperspeedcube"
ProductVersion = "2.0.0-pre.10"
OriginalFilename = "hyperspeedcube.exe"
LegalCopyright = "Copyright © 2024 HactarCE"

[package.metadata.bundle]
name = "Hyperspeedcube"
identifier = "dev.ajfarkas.hyperspeedcube"
icon = ["resources/icon/*.png", "resources/icon/*.ico"]
copyright = "Copyright © 2024 HactarCE"
category = "Puzzle Game"
