[package]
name = "hyperspeedcube"
version = "2.0.0-dev"
authors = ["HactarCE"]
edition = "2021"
rust-version = "1.68"
homepage = "https://ajfarkas.dev/hyperspeedcube/"
description = "Multidimensional twisty puzzle simulator"
repository = "https://github.com/HactarCE/Hyperspeedcube/"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.65"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
bytemuck = { version = "1.9.1", features = ["derive"] }
cgmath = "0.18.0"
config = "0.13.1"
dark-light = "0.2.1"
directories = "4.0.1"
egui = "0.21.0"
egui_dock = "0.4.2"
egui-wgpu = "0.21.0"
enum-iterator = "1.4.0"
env_logger = "0.10.0"
getrandom = { version = "*", features = ["js"] } # TODO: prefer `rand` crate
hex = "0.4.3"
instant = "0.1.12"
itertools = "0.10.3"
key-names = { git = "https://github.com/HactarCE/key-names", tag = "v1.5.1", features = ["winit"] }
lazy_static = "1.4.0"
log = "0.4.17"
monostate = "0.1.1"
num_enum = "0.5.7"
once_cell = "1.9.0"
optick = { version = "1.3.4", optional = true }
optick-attr = { version = "0.3.0", optional = true }
parking_lot = "0.12.1"
png = "0.17.5"
pollster = "0.2.5"
regex = "1.6.0"
rfd = "0.10.0"
send_wrapper = "0.6"
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.8.23"
smallvec = { version = "1.8.0", features = ["serde", "union"] }
strum = { version = "0.24.0", features = ["derive"] }
time = { version = "0.3.7", features = ["local-offset"] }
wgpu = { version = "0.15.1", features = ["webgl"] }
winit = { version = "0.28.3", features = ["serde"] }

ndpuzzle = { path = "../ndpuzzle" }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui-winit = { version = "0.21" }
human-panic = "1.0"
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
egui-winit = { version = "0.21", default-features = false, features = ["links"] }
js-sys = "=0.3.61"
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
web-sys = { version = "=0.3.61", features = [
    "CanvasRenderingContext2d",
    "Clipboard",
    "ClipboardEvent",
    "DataTransfer",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Storage",
    "Window",
] }

[features]
optick = ["dep:optick", "dep:optick-attr"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
FileDescription = "Hyperspeedcube"
ProductName = "Hyperspeedcube"
ProductVersion = "2.0.0-dev"
OriginalFilename = "hyperspeedcube.exe"
LegalCopyright = "Copyright © 2022 HactarCE"

[package.metadata.bundle]
name = "Hyperspeedcube"
identifier = "dev.ajfarkas.hyperspeedcube"
icon = ["resources/icon/*.png", "resources/icon/*.ico"]
copyright = "Copyright © 2022 HactarCE"
category = "Puzzle Game"
