[package]
name = "hyperpuzzle"
description = "Multidimensional twisty puzzle generator and simulator backend"
version = "0.1.0"
authors = ["Andrew Farkas"]
edition = "2021"
repository = "https://github.com/HactarCE/Hyperspeedcube/"
keywords = [
    "math", "geometry", "puzzle", "rubiks-cube",
    "conformal-geometric-algebra"
]
categories = ["mathematics", "algorithms", "computational-geometry"]
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.65"
enum-iterator = "1.4.1"
itertools = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.17"
parking_lot = "0.12.1"
rand = "0.8.5"
rlua = "0.19.5"

hypermath = { path = "../hypermath" }
hypershape = { path = "../hypershape" }
