[package]
name = "hyperpuzzlescript"
description = "Domain-specific language for defining puzzles for Hyperspeedcube"
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords = ["cubing", "hypercubing", "rubik", "4d"]
categories = ["algorithms", "mathematics", "simulation"]
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
hypermath = { workspace = true }
hyperpaths = { workspace = true, optional = true }
hyperpuzzle_core = { workspace = true }
hyperpuzzle_impl_nd_euclid = { workspace = true }
# hypershape = { workspace = true }

arcstr = { workspace = true }
ariadne = { workspace = true }
chumsky = { workspace = true }
# disjoint = { workspace = true }
ecow = { workspace = true }
eyre = { workspace = true } # TODO: make this optional if factoring puzzle construction into another crate
# float-ord = { workspace = true }
include_dir = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
# rayon = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }

# Color conversions
ecolor = { workspace = true, optional = true }
oklab = { workspace = true, optional = true }
