---
gfx:
  msaa: true
view:
  Rubiks33:
    pitch: 35.0
    yaw: -20.0
    scale: 1.25
    fov_3d: 30.0
    fov_4d: 30.0
    face_spacing: 0.025
    sticker_spacing: 0.05
    outline_thickness: 2.0
    light_intensity: 0.0
    light_pitch: 0.0
    light_yaw: 0.0
  Rubiks34:
    pitch: 30.0
    yaw: -35.0
    scale: 2.0
    fov_3d: 30.0
    fov_4d: 30.0
    face_spacing: 0.7
    sticker_spacing: 0.3
    outline_thickness: 1.0
    light_intensity: 1.0
    light_pitch: 65.0
    light_yaw: -55.0
outlines:
  default_size: 1.0
  hidden_size: 0.0
  hovered_size: 1.0
  default_color: "#000000"
  hidden_color: "#000000"
  hovered_color: "#ffffff"
colors:
  default_opacity: 1.0
  hidden_opacity: 0.3
  hovered_opacity: 1.0
  background: "#444444"
  blind_face: "#cccccc"
  blindfold: false
  faces:
    Rubiks33:
      B: "#4488ff"
      D: "#ffff00"
      L: "#ff9922"
      R: "#cc3333"
      U: "#ffffff"
      F: "#66cc44"
    Rubiks34:
      I: "#8822cc"
      B: "#ffff00"
      D: "#88ee66"
      L: "#ff9922"
      R: "#cc3333"
      U: "#33aaff"
      F: "#ffffff"
      O: "#ff66ff"
interaction:
  confirm_discard_only_when_scrambled: true
  highlight_piece_on_hover: true
  selection_fade_duration: 0.1
  hover_fade_duration: 0.1
  twist_duration: 0.2
  dynamic_twist_speed: true
general_keybinds:
  - vk: O
    ctrl: true
    command: open
  - vk: S
    ctrl: true
    command: save
  - vk: S
    ctrl: true
    shift: true
    command: save_as
  - vk: Q
    ctrl: true
    command: exit
  - vk: Z
    ctrl: true
    command: undo
  - vk: Z
    ctrl: true
    shift: true
    command: redo
  - vk: Y
    ctrl: true
    command: redo
  - vk: R
    ctrl: true
    command: reset
  - vk: B
    ctrl: true
    command: toggle_blindfold
  - vk: F3
    command:
      new_puzzle: Rubiks33
  - vk: F4
    command:
      new_puzzle: Rubiks34
  - vk: F
    ctrl: true
    command: scramble_full
puzzle_keybinds:
  Rubiks33:
    - sc: ShiftLeft
      command:
        hold_select:
          layers: 3
    - sc: ShiftRight
      command:
        hold_select:
          layers: 3
    - sc: KeyE
      command:
        twist:
          face: Left
          direction: CCW
          layers: 1
    - sc: KeyD
      command:
        twist:
          face: Left
          direction: CW
          layers: 1
    - sc: KeyI
      command:
        twist:
          face: Right
          direction: CW
          layers: 1
    - sc: KeyK
      command:
        twist:
          face: Right
          direction: CCW
          layers: 1
    - sc: KeyR
      command:
        twist:
          face: Left
          direction: CCW
          layers: 2
    - sc: KeyV
      command:
        twist:
          face: Left
          direction: CW
          layers: 2
    - sc: KeyU
      command:
        twist:
          face: Right
          direction: CW
          layers: 2
    - sc: KeyM
      command:
        twist:
          face: Right
          direction: CCW
          layers: 2
    - sc: KeyF
      command:
        twist:
          face: Up
          direction: CCW
          layers: 1
    - sc: KeyJ
      command:
        twist:
          face: Up
          direction: CW
          layers: 1
    - sc: KeyS
      command:
        twist:
          face: Down
          direction: CW
          layers: 1
    - sc: KeyL
      command:
        twist:
          face: Down
          direction: CCW
          layers: 1
    - sc: KeyG
      command:
        twist:
          face: Front
          direction: CCW
          layers: 1
    - sc: KeyH
      command:
        twist:
          face: Front
          direction: CW
          layers: 1
    - sc: KeyW
      command:
        twist:
          face: Back
          direction: CW
          layers: 1
    - sc: KeyO
      command:
        twist:
          face: Back
          direction: CCW
          layers: 1
    - sc: KeyT
      command:
        twist:
          face: Left
          direction: CCW
          layers: 7
    - sc: KeyB
      command:
        twist:
          face: Left
          direction: CW
          layers: 7
    - sc: KeyY
      command:
        twist:
          face: Right
          direction: CW
          layers: 7
    - sc: KeyN
      command:
        twist:
          face: Right
          direction: CCW
          layers: 7
    - sc: KeyA
      command:
        recenter:
          face: Left
    - sc: Semicolon
      command:
        recenter:
          face: Right
    - sc: KeyQ
      command:
        twist:
          face: Front
          direction: CCW
          layers: 7
    - sc: KeyP
      command:
        twist:
          face: Front
          direction: CW
          layers: 7
    - sc: KeyZ
      command:
        twist:
          face: Front
          direction: CCW
          layers: 2
    - sc: Slash
      command:
        twist:
          face: Front
          direction: CW
          layers: 2
    - sc: KeyX
      command:
        twist:
          face: Down
          direction: CW
          layers: 2
    - sc: Period
      command:
        twist:
          face: Down
          direction: CCW
          layers: 2
  Rubiks34:
    - sc: ShiftLeft
      command:
        hold_select:
          layers: 3
    - sc: ShiftRight
      command:
        hold_select:
          layers: 3
    - sc: AltLeft
      command:
        hold_select:
          layers: 2
    - sc: AltRight
      command:
        hold_select:
          layers: 2
    - sc: KeyW
      command:
        hold_select:
          face: Left
    - sc: KeyE
      command:
        hold_select:
          face: Up
    - sc: KeyR
      command:
        hold_select:
          face: Back
    - sc: KeyS
      command:
        hold_select:
          face: Front
    - sc: KeyD
      command:
        hold_select:
          face: In
    - sc: KeyF
      command:
        hold_select:
          face: Right
    - sc: KeyC
      command:
        hold_select:
          face: Down
    - sc: KeyV
      command:
        hold_select:
          face: Out
    - sc: Digit1
      shift: true
      command:
        toggle_select:
          piece_type: 1c
    - sc: Digit2
      shift: true
      command:
        toggle_select:
          piece_type: 2c
    - sc: Digit3
      shift: true
      command:
        toggle_select:
          piece_type: 3c
    - sc: Digit4
      shift: true
      command:
        toggle_select:
          piece_type: 4c
    - sc: Digit1
      shift: true
      command: none
    - sc: Digit2
      shift: true
      command: none
    - sc: Digit3
      shift: true
      command: none
    - sc: Digit4
      shift: true
      command: none
    - sc: Digit1
      command:
        hold_select:
          piece_type: 1c
    - sc: Digit2
      command:
        hold_select:
          piece_type: 2c
    - sc: Digit3
      command:
        hold_select:
          piece_type: 3c
    - sc: Digit4
      command:
        hold_select:
          piece_type: 4c
    - sc: Escape
      command:
        clear_toggle_select: piece_type
    - sc: KeyI
      command:
        twist:
          direction: x
          layers: 1
    - sc: KeyK
      command:
        twist:
          direction: "x'"
          layers: 1
    - sc: KeyJ
      command:
        twist:
          direction: y
          layers: 1
    - sc: KeyL
      command:
        twist:
          direction: "y'"
          layers: 1
    - sc: KeyU
      command:
        twist:
          direction: "z'"
          layers: 1
    - sc: KeyO
      command:
        twist:
          direction: z
          layers: 1
    - sc: Space
      command:
        recenter: {}
    - sc: KeyT
      command:
        twist:
          face: In
          direction: x
          layers: 7
    - sc: KeyY
      command:
        twist:
          face: In
          direction: x
          layers: 7
    - sc: KeyB
      command:
        twist:
          face: In
          direction: "x'"
          layers: 7
    - sc: KeyN
      command:
        twist:
          face: In
          direction: "x'"
          layers: 7
    - sc: KeyA
      command:
        twist:
          face: In
          direction: "y'"
          layers: 7
    - sc: Semicolon
      command:
        twist:
          face: In
          direction: y
          layers: 7
    - sc: KeyQ
      command:
        twist:
          face: In
          direction: "z'"
          layers: 7
    - sc: KeyP
      command:
        twist:
          face: In
          direction: z
          layers: 7
info:
  metric: STM
  keybinds_reference:
    function: false
    navigation: false
    numpad: false
    opacity: 1.0
