---
gfx:
  fps: 60
  font_size: 16.0
  msaa: "8"
  label_size: 24.0
info:
  metric: QSTM
view:
  Rubiks3D:
    pitch: 35.0
    yaw: 0.0
    scale: 1.25
    fov_3d: 30.0
    fov_4d: 30.0
    face_spacing: 0.025
    sticker_spacing: 0.05
    outline_thickness: 2.0
  Rubiks4D:
    pitch: 30.0
    yaw: -35.0
    scale: 2.0
    fov_3d: 30.0
    fov_4d: 30.0
    face_spacing: 0.7
    sticker_spacing: 0.3
    outline_thickness: 1.5
colors:
  sticker_opacity: 1.0
  hidden_opacity: 0.1
  faces:
    Rubiks3D:
      B: "#4488ff"
      D: "#ffff00"
      L: "#ff9922"
      R: "#cc3333"
      U: "#ffffff"
      F: "#66cc44"
    Rubiks4D:
      I: "#9944dd"
      B: "#ffff00"
      D: "#88ee66"
      L: "#ff9922"
      R: "#cc3333"
      U: "#33aaff"
      F: "#ffffff"
      O: "#ff55ff"
  blind_face: "#000000"
  background: "#666666"
  outline: "#000000"
general_keybinds:
  - vk: O
    ctrl: true
    command: open
  - vk: S
    ctrl: true
    command: save
  - vk: S
    ctrl: true
    shift: true
    command: save_as
  - vk: Q
    ctrl: true
    command: exit
  - vk: Z
    ctrl: true
    command: undo
  - vk: Z
    ctrl: true
    shift: true
    command: redo
  - vk: Y
    ctrl: true
    command: redo
  - vk: R
    ctrl: true
    command: reset
  - vk: F3
    command:
      new_puzzle: Rubiks3D
  - vk: F4
    command:
      new_puzzle: Rubiks4D
puzzle_keybinds:
  Rubiks3D:
    - sc: ShiftLeft
      command:
        hold_select:
          layers: 3
    - sc: ShiftRight
      command:
        hold_select:
          layers: 3
    - sc: KeyE
      command:
        twist:
          face: Left
          layers: 1
          direction: CCW
    - sc: KeyD
      command:
        twist:
          face: Left
          layers: 1
          direction: CW
    - sc: KeyI
      command:
        twist:
          face: Right
          layers: 1
          direction: CW
    - sc: KeyK
      command:
        twist:
          face: Right
          layers: 1
          direction: CCW
    - sc: KeyR
      command:
        twist:
          face: Left
          layers: 2
          direction: CCW
    - sc: KeyV
      command:
        twist:
          face: Left
          layers: 2
          direction: CW
    - sc: KeyU
      command:
        twist:
          face: Right
          layers: 2
          direction: CW
    - sc: KeyM
      command:
        twist:
          face: Right
          layers: 2
          direction: CCW
    - sc: KeyF
      command:
        twist:
          face: Up
          layers: 1
          direction: CCW
    - sc: KeyJ
      command:
        twist:
          face: Up
          layers: 1
          direction: CW
    - sc: KeyS
      command:
        twist:
          face: Down
          layers: 1
          direction: CW
    - sc: KeyL
      command:
        twist:
          face: Down
          layers: 1
          direction: CCW
    - sc: KeyG
      command:
        twist:
          face: Front
          layers: 1
          direction: CCW
    - sc: KeyH
      command:
        twist:
          face: Front
          layers: 1
          direction: CW
    - sc: KeyW
      command:
        twist:
          face: Back
          layers: 1
          direction: CW
    - sc: KeyO
      command:
        twist:
          face: Back
          layers: 1
          direction: CCW
    - sc: KeyT
      command:
        twist:
          face: Left
          layers: 7
          direction: CCW
    - sc: KeyB
      command:
        twist:
          face: Left
          layers: 7
          direction: CW
    - sc: KeyY
      command:
        twist:
          face: Right
          layers: 7
          direction: CW
    - sc: KeyN
      command:
        twist:
          face: Right
          layers: 7
          direction: CCW
    - sc: KeyA
      command:
        recenter:
          face: Left
    - sc: Semicolon
      command:
        recenter:
          face: Right
    - sc: KeyQ
      command:
        twist:
          face: Front
          layers: 7
          direction: CCW
    - sc: KeyP
      command:
        twist:
          face: Front
          layers: 7
          direction: CW
    - sc: KeyZ
      command:
        twist:
          face: Front
          layers: 2
          direction: CCW
    - sc: Slash
      command:
        twist:
          face: Front
          layers: 2
          direction: CW
    - sc: KeyX
      command:
        twist:
          face: Down
          layers: 2
          direction: CW
    - sc: Period
      command:
        twist:
          face: Down
          layers: 2
          direction: CCW
  Rubiks4D:
    - sc: ShiftLeft
      command:
        hold_select:
          layers: 3
    - sc: ShiftRight
      command:
        hold_select:
          layers: 3
    - sc: AltLeft
      command:
        hold_select:
          layers: 2
    - sc: AltRight
      command:
        hold_select:
          layers: 2
    - sc: KeyW
      command:
        hold_select:
          face: Left
    - sc: KeyE
      command:
        hold_select:
          face: Up
    - sc: KeyR
      command:
        hold_select:
          face: Back
    - sc: KeyS
      command:
        hold_select:
          face: Front
    - sc: KeyD
      command:
        hold_select:
          face: In
    - sc: KeyF
      command:
        hold_select:
          face: Right
    - sc: KeyC
      command:
        hold_select:
          face: Down
    - sc: KeyV
      command:
        hold_select:
          face: Out
    - sc: Digit1
      shift: true
      command:
        toggle_select:
          piece_type: 1c
    - sc: Digit2
      shift: true
      command:
        toggle_select:
          piece_type: 2c
    - sc: Digit3
      shift: true
      command:
        toggle_select:
          piece_type: 3c
    - sc: Digit4
      shift: true
      command:
        toggle_select:
          piece_type: 4c
    - sc: Digit1
      shift: true
      command: none
    - sc: Digit2
      shift: true
      command: none
    - sc: Digit3
      shift: true
      command: none
    - sc: Digit4
      shift: true
      command: none
    - sc: Digit1
      command:
        hold_select:
          piece_type: 1c
    - sc: Digit2
      command:
        hold_select:
          piece_type: 2c
    - sc: Digit3
      command:
        hold_select:
          piece_type: 3c
    - sc: Digit4
      command:
        hold_select:
          piece_type: 4c
    - sc: Escape
      command:
        clear_toggle_select: piece_type
    - sc: KeyI
      command:
        twist:
          layers: 1
          direction: x
    - sc: KeyK
      command:
        twist:
          layers: 1
          direction: "x'"
    - sc: KeyJ
      command:
        twist:
          layers: 1
          direction: y
    - sc: KeyL
      command:
        twist:
          layers: 1
          direction: "y'"
    - sc: KeyU
      command:
        twist:
          layers: 1
          direction: "z'"
    - sc: KeyO
      command:
        twist:
          layers: 1
          direction: z
    - sc: Space
      command:
        recenter: {}
    - sc: KeyT
      command:
        twist:
          face: In
          layers: 7
          direction: x
    - sc: KeyY
      command:
        twist:
          face: In
          layers: 7
          direction: x
    - sc: KeyB
      command:
        twist:
          face: In
          layers: 7
          direction: "x'"
    - sc: KeyN
      command:
        twist:
          face: In
          layers: 7
          direction: "x'"
    - sc: KeyA
      command:
        twist:
          face: In
          layers: 7
          direction: "y'"
    - sc: Semicolon
      command:
        twist:
          face: In
          layers: 7
          direction: y
    - sc: KeyQ
      command:
        twist:
          face: In
          layers: 7
          direction: "z'"
    - sc: KeyP
      command:
        twist:
          face: In
          layers: 7
          direction: z
