[package]
name = "hyperstrings"
description = "Opinionated localization and static string management library"
version = "0.1.0"
authors = ["Andrew Farkas"]
edition.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["i18n", "l10n", "strings"]
categories = ["internationalization", "localization"]
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
ident_case = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
kdl = { workspace = true }
lazy_static = { workspace = true }
owo-colors = { workspace = true }
regex = { workspace = true }
unindent = { workspace = true }
